[build]
	command = "npm run build"
	publish = "build"
	ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
[build.environment]
	NODE_VERSION = "20"
[build.processing]
  skip_processing = false